### ISSUE TITLE
[🐞] Response headers/status not set from FastAPI sub response 

### ISSUE THREAD

**Issue by LittleLampLight** [smagafurov/fastapi-jsonrpc#12]
Currently it's impossible to set headers/cookies/status code via [FastAPI response param](https://fastapi.tiangolo.com/advanced/response-headers/#use-a-response-parameter)

reason is: ignored `sub_response` [variable returned from request dependency resolver.](https://github.com/smagafurov/fastapi-jsonrpc/blob/master/fastapi_jsonrpc/__init__.py#L626)

[missing code fragment](https://github.com/tiangolo/fastapi/blob/master/fastapi/routing.py#L206)

currently hot fix seems not possible because response object is creating outside scope of `solve_dependencies` call

**Comment by smagafurov** [comment]
done: 0.3.1
