### ISSUE TITLE
В swagger в Example Value выставляется неверное значение версии jsonrpc

### ISSUE THREAD

**Issue by DianaArapova** [smagafurov/fastapi-jsonrpc#16]
В swagger в примере запросе поле "jsonrpc" выставляется равным 2, как число. Необходимо, чтобы выставлялось "2.0", как строка.

<img width="242" alt="image" src="https://user-images.githubusercontent.com/32325160/104911273-6b0a0d80-59ac-11eb-9e09-c01ed4e5ad34.png">

<img width="422" alt="image" src="https://user-images.githubusercontent.com/32325160/104911303-79f0c000-59ac-11eb-83ab-762d4de15f96.png">

Есть предположение что, если [тут](https://github.com/smagafurov/fastapi-jsonrpc/blob/master/fastapi_jsonrpc/__init__.py#L354) значение example='"2.0"', то тогда swagger автоматом не преобразовывал бы это значение в численное.

Версия библиотеки fastapi-jsonrpc==2.0.2, pydantic==1.7.3

**Comment by smagafurov** [comment]
Судя по всему, проблема где-то на стороне fastapi.
Надо куда-то туда issue писать
Здесь мы разве что можем какой-то воркараунд найти
Если найдете воркараунд, присылайте пул реквест

**Comment by smagafurov** [comment]
Последняя версия, с которой нормально работает: fastapi-0.61.1

Надо посмотреть, что они поменяли в версии: fastapi-0.61.2

**Comment by smagafurov** [comment]
Вот из-за этого сломалось: https://github.com/tiangolo/fastapi/pull/2089/files

**Comment by smagafurov** [comment]
Вот из-за этого изменения в swagger-е в версии 3.40.0: https://github.com/swagger-api/swagger-ui/pull/6827

**Comment by smagafurov** [comment]
Написал там коммент в swagger, что они поломали у себя

Думаю лучше дождаться, когда они починят

А пока можно жить на версии: fastapi-0.61.1

**Comment by smagafurov** [comment]
swagger починили, я проверил, заработало

только пришлось кеш браузера почистить, чтобы новый swagger подтянулся
