### ISSUE TITLE
License

### ISSUE THREAD

**Issue by jcubic** [smagafurov/fastapi-jsonrpc#19]
Is this project Open Source? If you don't add a license, it's not Open Source even if the code is public. By default, everything is copyrighted (all right reserved) even if not explicitly written. That's why there are licenses that circumvent that.

**Comment by rhkleijn** [comment]
The setup.py file indicates a MIT license: https://github.com/smagafurov/fastapi-jsonrpc/blob/9d9190f8013b50f71be26b0dcb96e86d932d1311/setup.py#L33

which is also shown in pypi, see https://pypi.org/project/fastapi-jsonrpc/

**Comment by smagafurov** [comment]
MIT LICENSE added
