### ISSUE TITLE
Providing an example value for a parameter

### ISSUE THREAD

**Issue by rhkleijn** [smagafurov/fastapi-jsonrpc#20]
I just encountered fastapi-jsonrpc and when trying the provided example:

```
import fastapi_jsonrpc as jsonrpc
from pydantic import BaseModel
from fastapi import Body


app = jsonrpc.API()

api_v1 = jsonrpc.Entrypoint('/api/v1/jsonrpc')


class MyError(jsonrpc.BaseError):
    CODE = 5000
    MESSAGE = 'My error'

    class DataModel(BaseModel):
        details: str


@api_v1.method(errors=[MyError])
def echo(
    data: str = Body(..., example='123'),
) -> str:
    if data == 'error':
        raise MyError(data={'details': 'error'})
    else:
        return data


app.bind_entrypoint(api_v1)


if __name__ == '__main__':
    import uvicorn
    uvicorn.run('example1:app', port=5000, debug=True, access_log=False)
```

it seems that the example value '123' of method `echo` does not end up correctly in the schema.
http://127.0.0.1:5000/docs shows this example

```
{
  "jsonrpc": "2.0",
  "id": 0,
  "method": "echo",
  "params": {
    "data": "string"
  }
}
```

where I would have expected it to be

```
{
  "jsonrpc": "2.0",
  "id": 0,
  "method": "echo",
  "params": {
    "data": "123"
  }
}
```

Is there a way to provide an example value for a parameter? 

Note: I would like it to be just an example value, it should not be used as a default value when the user omits it. E.g. `data: str = '123'` does show `'123'` as an example value, but it would also act as a default value when the request omits the `data` parameter.

**Comment by smagafurov** [comment]
This behaviour is inherited from [fastapi](https://github.com/tiangolo/fastapi)

May be there is some bug in some version of fastapi

You can try to update fastapi

Or ask this question in fastapi repository
