### ISSUE TITLE
Possible to have a function with json return type or no return type at all act as a route?

### ISSUE THREAD

**Issue by csajedi** [smagafurov/fastapi-jsonrpc#3]
So I want to use you jsonrpc implementation for its numerous benefits, but when I try to combine it with some functions that return JSON strings I cannot seem to get the response configuration right.
When I run it with json return type I get an error, when I try to use a class implementing BaseModel and containing the json element, then it runs the server but responses error the server out.
If you want to see the code, its basically:

```python
from pydantic import json
@api_v1.method()
def consistency(past_root:str) -> json:
```

which I would be fine removing the json return type, but the value it responds with to the client should absolutely be this json string. I feel that I am missing something, being a beginner at fastapi and your library as well. The code in question can be found [here](https://github.com/starling-foundries/Data-Timestamp/blob/feature/rpc/src/app/main.py).

**Comment by denisSurkov** [comment]
Check [how fast API solves this problem](https://fastapi.tiangolo.com/features/#validation). If you want to annotate you return's type you should use `def foo() -> dict:` (dict = json). So just return a dict from your view and the lib will do its job.

Hint: 
It's better to return plain dict from your service function `proof_from()`, and then return dict from api view.

```
...
        # proof_from()
        proof = self.merkle.merkleProof({'checksum': digest}).serialize()
        print(proof)
        return proof
...
```

The result would like: 
```
{
  "jsonrpc": "2.0",
  "id": 0,
   "result": { _your object from proof_from()_ }
}
```

**Comment by csajedi** [comment]
Thank you, this solved my issue. great library!
