### ISSUE TITLE
Possible incorrect parsing of JSON RPC request: params considered required

### ISSUE THREAD

**Issue by mike-hart** [smagafurov/fastapi-jsonrpc#32]
Hi,

With the following test code:

```python
import fastapi_jsonrpc as jsonrpc

app = jsonrpc.API()
api = jsonrpc.Entrypoint("/")

@api.method()
def simple() -> None:
    return None

app.bind_entrypoint(api)
```
executed as `bin/uvicorn example_service:app --port 6666` and accessed using curl, we get the following:
```
$ curl -sX POST -d '{"jsonrpc": "2.0", "id": 0, "method": "simple", "params":[]}' -H 'Content-Type: application/json' http://127.0.0.1:6666/ | jq
{
  "jsonrpc": "2.0",
  "result": null,
  "id": 0
}
```

But if we try calling without a params element (as described legal in the JSON RPC spec, emphasis mine) - https://www.jsonrpc.org/specification#request_object
> params
>    A Structured value that holds the parameter values to be used during the invocation of the method. **This member MAY be omitted**.

We get the following:
```
curl -sX POST -d '{"jsonrpc": "2.0", "id": 0, "method": "simple"}' -H 'Content-Type: application/json' http://127.0.0.1:6666/ | jq
{
  "jsonrpc": "2.0",
  "error": {
    "code": -32600,
    "message": "Invalid Request",
    "data": {
      "errors": [
        {
          "loc": [
            "params"
          ],
          "msg": "field required",
          "type": "value_error.missing"
        }
      ]
    }
  },
  "id": 0
}
```

I believe this may be able to be fixed by changing https://github.com/smagafurov/fastapi-jsonrpc/blob/master/fastapi_jsonrpc/__init__.py#L368 from:
```python
    params: dict
```
to
```python
    params: dict = Field(default_factory=dict)
```

But I'm not 100% sure what follow-on effects this may have (if any).

**Comment by smagafurov** [comment]
fixed

fastapi-jsonrpc (2.4.1)
