### ISSUE TITLE
Query Parameter

### ISSUE THREAD

**Issue by fgiudici95** [smagafurov/fastapi-jsonrpc#35]
Hi,

Does this library support the usage of the query parameters?
(example: POST http://127.0.0.1:8000/api/v1/jsonrpc?skip=10)

If yes, can you provide an example?

Thank you!
Fabio

**Comment by smagafurov** [comment]
yes

see fatsapi examples

**Comment by smagafurov** [comment]
Something like this I guess:

```python
def get_skip(
    skip: int = 0,
) -> int:
    return skip

api_v1 = Entrypoint(
    '/api/v1/jsonrpc',
    dependencies=[Depends(get_skip)],
)
```
