### ISSUE TITLE
New FastAPI version breaks fastapi-jsonrpc

### ISSUE THREAD

**Issue by VincentHch** [smagafurov/fastapi-jsonrpc#37]
Following release 0.18.0 of Starlette accepted by FastAPI in [0.76.0](https://fastapi.tiangolo.com/release-notes/#0760), `starlette.Response` object does not accept `None` value anymore for `status_code` ([starlette/responses.py#L77](https://github.com/encode/starlette/blob/0.18.0/starlette/responses.py#L77)).
This breaks the [EntrypointRoute.handle_http_request](https://github.com/smagafurov/fastapi-jsonrpc/blob/v2.2.0/fastapi_jsonrpc/__init__.py#L1039-L1045) function.

A fix might be possible, but freezing dependencies would be safer to avoid future issue with future updates.

**To reproduce:**

This minimal example does not work anymore

```python
# main.py
import fastapi_jsonrpc as jsonrpc

app = jsonrpc.API()
api_v1 = jsonrpc.Entrypoint('/api/v1/jsonrpc')

@api_v1.method()
def echo(
    x: int,
) -> int:
    return x

app.bind_entrypoint(api_v1)

if __name__ == '__main__':
    import uvicorn
    uvicorn.run('main:app', port=5000, debug=True, access_log=False)
```

```
pip install fastapi==0.76.0
```
```
python main.py
```

```
curl --request POST \
  --url http://localhost:5000/api/v1/jsonrpc \
  --header 'Content-Type: application/json' \
  --data '{
	"method": "echo",
	"id": "1",
	"params": {
	    "x": 1
	}
}'
```

**Comment by smagafurov** [comment]
Let's replace this lines:

https://github.com/smagafurov/fastapi-jsonrpc/blob/v2.2.0/fastapi_jsonrpc/__init__.py#L1039-L1045

with this line:

https://github.com/tiangolo/fastapi/blob/b44e85ca8a6e6cdf59c4da2541b12de808a0f539/fastapi/dependencies/utils.py#L466

i.e. let's create sub_response just like fastapi does.

Can you create such pull request?

**Comment by smagafurov** [comment]
Pushed a commit that referenced this issue [13]: https://github.com/smagafurov/fastapi-jsonrpc/commit/6b738295c9be0d0ec44c604630dc9091fcba72d3

**Comment by VincentHch** [comment]
> Can you create such pull request?

Sure: #39
