### ISSUE TITLE
clone_dependant() fakes cloning 

### ISSUE THREAD

**Issue by denisSurkov** [smagafurov/fastapi-jsonrpc#4]
**The problem:**
`clone_dependant()` seems to copy the dependant, but it's not. When you try to append something to cloned dependant's fields you edit the original fields too.

```
cloned_dependant = clone_dependant(original_dependant)

original_dependant.body_params.append("some value that should be in copied")
assert cloned_dependant.body_params == ["some path"]  # fails
```

**Comment by spumer** [comment]
Looks like obsolete. Waiting for use-case to reopen issue
