### ISSUE TITLE
Upgrade to FastAPI >= 0.80

### ISSUE THREAD

**Issue by ksmolyanin** [smagafurov/fastapi-jsonrpc#43]
Currently this library is limited to not to be used with FastAPI greater then 0.80 but FastAPI has already released ver. 0.86. Is it possible to change this limitation, please?

```
pyproject.toml
fastapi = ">0.55,<0.80"
```

**Comment by spumer** [comment]
Looks like we can up to 0.86.0

https://github.com/smagafurov/fastapi-jsonrpc/actions/runs/3407488734

@smagafurov

**Comment by smagafurov** [comment]
done

fastapi-jsonrpc (2.4.0)
