### ISSUE TITLE
Unhandled UnicodeDecodeError when parsing body 

### ISSUE THREAD

**Issue by MarwinBl** [smagafurov/fastapi-jsonrpc#48]
Hi, colleagues! Sometime I have non-json requests in my handlers (like form with file inside) and application crashes with UnicodeDecodeError. I think this error is ok to catch in [parse_body](https://github.com/smagafurov/fastapi-jsonrpc/blob/master/fastapi_jsonrpc/__init__.py#LL737C22-L737C22) and throw `ParseError`.

**Comment by spumer** [comment]
>application crashes with UnicodeDecodeError

You mean `app crash` when process terminated or just return InternalError?

**Comment by MarwinBl** [comment]
just InternalError
