### ISSUE TITLE
Handle pydantic v2

### ISSUE THREAD

**Issue by sam-courtemanche-wmx** [smagafurov/fastapi-jsonrpc#50]
As of version [0.100.0](https://github.com/tiangolo/fastapi/releases/tag/0.100.0), Fastapi now handles Pydantic v2.

There is at least one issue preventing it to work with this package:

```python3
fastapi_jsonrpc/__init__.py:13
ImportError: cannot import name 'DictError' from 'pydantic'
```

From what I have tested, removing the missing imports or trying to import pydantic models from `pydantic.v1` is not enough, this will probably require some design update

**Comment by xunto** [comment]
Is this worked on? We are starting a new project right now, and it would be cool to use the lastest Pydantic, and not the old one...

**Comment by spumer** [comment]
Work in progress. 14 tests failed, 68 passed.
Will release on next week :)

**Comment by spumer** [comment]
we publish `3.0.0b` version, now you can test it with new fastapi and new pydantic v2
