### ISSUE TITLE
Logging access

### ISSUE THREAD

**Issue by denisSurkov** [smagafurov/fastapi-jsonrpc#7]
Because client makes post on only one route it's hard to tell what is request

Maybe it's not about this library, but it would be really useful to have this feature out of the box.

**Comment by denisSurkov** [comment]
Maybe this jsonrpc feature for fastapi should expand `Request` object

https://fastapi.tiangolo.com/advanced/custom-request-and-route/

**Comment by spumer** [comment]
I actually can't understand what do you want to do, but ... 

Custom Request class now allowed by PR #21 

And logging can be done via middleware starting from https://github.com/smagafurov/fastapi-jsonrpc/commit/bf073d641b4c9a8bdbbe8908401ace9e751a1adc, see README.rst

**Comment by denisSurkov** [comment]
Yes, not it's pretty easy to do. But issue was created a while ago. So now it is not relevant, so I close it.
